### ISSUE TITLE
Torrent with seeds and peers but still not downloading (Stalled)

### ISSUE THREAD

**Issue by mrr010** [c0re100/qBittorrent-Enhanced-Edition#30]
**Please provide the following information**

### qBittorrent version and Operating System
4.1.5.1

### If on linux, libtorrent and Qt version
(type here)

### What is the problem
![default](https://user-images.githubusercontent.com/47032166/51749622-d46f2280-20ea-11e9-8c6d-b385e93aa3d1.png)

Torrent with seeds and peers but still not downloading (Stalled)

### What is the expected behavior
(type here)

### Steps to reproduce
(type here)

### Extra info(if any)
DHT PeX enabled

**Comment by c0re100** [comment]
> **Please provide the following information**
> 
> ### qBittorrent version and Operating System
> 4.1.5.1
> 
> ### If on linux, libtorrent and Qt version
> (type here)
> 
> ### What is the problem
> ![default](https://user-images.githubusercontent.com/47032166/51749622-d46f2280-20ea-11e9-8c6d-b385e93aa3d1.png)
> 
> Torrent with seeds and peers but still not downloading (Stalled)
> 
> ### What is the expected behavior
> (type here)
> 
> ### Steps to reproduce
> (type here)
> 
> ### Extra info(if any)
> DHT PeX enabled

Due to Torrent Queuing feature enabled by default.
If unfinished/new torrent more than that queue limit, qBit will be download torrent sequentially.
You can see the queue number(order/priority) here.
![51749622-d46f2280-20ea-11e9-8c6d-b385e93aa3d1](https://user-images.githubusercontent.com/5726473/51778405-72d7a400-213c-11e9-828e-6f052680f44f.png)
Also, you can disable or increase the limit in Options.
![default](https://user-images.githubusercontent.com/5726473/51778575-6b64ca80-213d-11e9-8c26-91d512541bb4.png)

**Comment by c0re100** [comment]
> ![default](https://user-images.githubusercontent.com/47032166/51783509-eea21280-2175-11e9-8c51-46a568584dfa.png)
> I set max queue and I have everything paused and still those torrent with seeds and peers are not downloading at all.

Do you have enable UPnP on your router? and port mapping is successfully?
You can view the port mapping message in the `execution log`
`26/1/2019 17:33 - UPnP/NAT-PMP: Port mapping successful, message: successfully mapped port using UPnP. external port: 12345`

**Comment by mrr010** [comment]
Yes, I have port mapping, I also add port forwarding in router settings.

**Comment by c0re100** [comment]
> No proxy server and I dont think my ISP is blocking anything here in Hong Kong, all those connections have file progress of 0%, but I dont know why qbittorrent is still connecting me to them.
> I cannot connect to seeds/peers which progress is not 0% in those torrents. However not all torrents have this issue, you can see some of my torrent do have progress, those that stuck at 99.X% is because the file availability is 99.X%, no one have the complete file in the network I guess.

I see. There are many reasons why the torrent not downloading (`Stalled`)...
1. Check the proxy settings here. it should be `(None)`
![default](https://user-images.githubusercontent.com/5726473/51800789-eaf2b680-226f-11e9-8975-84d952945a97.png)
2. Check the seed's peers widget. It should shown all connected peers information.
I guess torrent seeder not uploading to other peers. 
![default](https://user-images.githubusercontent.com/5726473/51800899-94867780-2271-11e9-90e9-46160a10ebe2.png)
3. Can you send a torrent url to my email for testing? corehusky@gmail.com

**Comment by mrr010** [comment]
![default](https://user-images.githubusercontent.com/47032166/51803468-809e3e00-2290-11e9-816a-c0a965977a23.png)
Most of the time shows 0% progress

**Comment by c0re100** [comment]
> ![default](https://user-images.githubusercontent.com/47032166/51803468-809e3e00-2290-11e9-816a-c0a965977a23.png)
> Most of the time shows 0% progress
> Confirm proxy is "none"
> 
> For my 1st torrent, there is bracket (127) under seeds, does it means there are 127 seeds that I can potentially connect to? If so, why am I not connecting to them? The number 3 not in bracket under seeds shows I am connected to 3 seeds? But why all my Peers connection shows 0 progress and nothing is downloading?

Yes, you can connect to this 127 seeders if peer and seeder's network doesn't sucks.
I can't download your example torrent too, all peers shows 0 progress and DHT/PeX/LSD/Tracker shown 0 `downloaded` (that means no one downloaded/completed this torrent.)
In this case, all of them are `FAKE Seeders/Torrents` possibly.
So no one can download from them.
OR original uploader may not start seeding in this time...

*FAKE Seeders/Torrents*: For example,  an automated bot send a request to tracker(s) say `HEY, my torrent completed.`, so that the tracker will mark my information to database and upload the peers list.
