### ISSUE TITLE
[Feature Request] Request periodical releases of qbittorrent-nox for Windows

### ISSUE THREAD

**Issue by Hanjingxue-Boling** [c0re100/qBittorrent-Enhanced-Edition#334]
### Suggestion

Request to add the qbittorrent-nox binary package for Windows in the GitHub release.

Consistent releases of qbittorrent-nox binaries are not required, but I would like to be able to occasionally find nox binaries on the release page so that I can update the software for feature improvements and bug fixes.

### Use case

When qbittorrent with GUI is started on Windows, if qbittorrent loads a lot of seeds (more than 30), it takes up a lot of hardware resources and has a significant impact on network connectivity. The whole process will take about five or ten minutes (v 4.4.1 will take longer to load).

The same happens with qbittorrent if there is a network change (e.g. switching to another network).

And if you intervene in this process, the software's GUI will not respond.

qbittorrent-nox has no such problems.

### Extra info/examples/attachments

The official wiki has a description of how to build qbittorrent from source. i read about it, but did not succeed in building it (the reason for my failure was probably my lack of knowledge and experience in compiling software).

Another reason was that I needed qbittorrent-enhanced-edition to help me resist the vampire (XunLei) downloads.

I couldn't find a way to ease the problems of the qbittorrent GUI, but I found that qbittorrent-nox can avoid the problems I'm having. So I hope the maintainer will continue to provide `qbittorrent-nox` for Windows 10/11 systems in the future. You don't need to follow the official ongoing releases, just release them periodically. This way users with similar needs can update qbittorrent-nox regularly without causing more stress to maintainers.

**Comment by abcfy2** [comment]
In fact qbittorrent-enhanced-edition 4.3 contains mingw64 nox build: https://github.com/c0re100/qBittorrent-Enhanced-Edition/releases/tag/release-4.3.9.10

But I've removed `x86_64-w64-mingw32` cross build from CI because it cannot compile successfully now.

First. `qbittorrent-nox` seems not working in Windows. Even though `x86_64-w64-mingw32` could compile successfully, you can't see any output in terminal, and you have to stop terminal in task manager.

And then, libtorrent cannot compile under `x86_64-w64-mingw32` for now. In the gcc old version can be fixed follow my issue: https://github.com/arvidn/libtorrent/issues/5330 , but gcc 11 not working any more, it's too hard for me to fix this issue.

**Comment by Hanjingxue-Boling** [comment]
Thanks for help!

**Comment by Hanjingxue-Boling** [comment]
> First. `qbittorrent-nox` seems not working in Windows. Even though `x86_64-w64-mingw32` could compile successfully, you can't see any output in terminal, and you have to stop process in task manager.

Are you saying that qbittorrent-nox does not respond to signals from the console on Windows?

But its webui works fine and responds to user actions.

**Comment by Hanjingxue-Boling** [comment]
It looks like the only way to use qbittorrent-nox is with Linux or docker.

Thanks for your work.
