### ISSUE TITLE
mac SSR Failed to load from URL

### ISSUE THREAD

**Issue by Ding-Kyoma** [c0re100/qBittorrent-Enhanced-Edition#395]
### qBittorrent & operating system versions

qBittorrent: 4.4.3.12 universal
Operating system: macOS 12.4 Arm (Apple chip)

### What is the problem?

I cannot download torrent file from SSR.

It seems that the program add a `.` at the end of the link. When I use Chinese Language, it add `。`at end of link.

### Steps to reproduce

I use this [SSR link](https://www.kisssub.org/rss-夏日重现+喵萌奶茶屋+1080+简日.xml) to download torrent. 

### Additional context

See a .。at the end of link...

<img width="1170" alt="image" src="https://user-images.githubusercontent.com/44542198/176733618-f0e8d895-0827-414e-9bb6-25791ad0ff3d.png">

<img width="1173" alt="image" src="https://user-images.githubusercontent.com/44542198/176734305-5c3add46-7f72-4a93-93ee-c664548f572f.png">

**Comment by Kolcha** [comment]
very likely dot at the end is just a part of UI, especially when it changes with display language.

also message states some specific error details, so this is definitely not related to fetching. moreover, according to error message, this error comes from magnet lint/torrent metadata decoding ("bencoded string" is a term from torrent implementation world), it has nothing with RSS (at least directly).

very likely the problem exists only with specific RSS feed or even only with one item in it. I'll try to figure out the reason.

**Comment by Kolcha** [comment]
so, I'm back. as I wrote above, the problem is only in this specific RSS feed - any "torrent URL" in this feed points to an HTML page with an error description ("Invalid code" in my case) rather than actual torrent data as it should be.
try [this URL](http://v2.uploadbt.com/?r=down&amp;hash=aa8e52b52954998205bed4a5e2c4580c5e114f90) for example, extracted from one of the top "articles" from the mentioned feed at the moment of writing.

the message you see (I also saw it) comes from the next path:

- the article is parsed https://github.com/c0re100/qBittorrent-Enhanced-Edition/blob/4ffc2ccce818b133e6355514234282e66c0ad5e9/src/base/rss/rss_parser.cpp#L631-L632
- item is double-clicked (condition is `true` in your case) https://github.com/c0re100/qBittorrent-Enhanced-Edition/blob/4ffc2ccce818b133e6355514234282e66c0ad5e9/src/gui/rss/rsswidget.cpp#L368-L374
- torrent downloading is scheduled https://github.com/c0re100/qBittorrent-Enhanced-Edition/blob/4ffc2ccce818b133e6355514234282e66c0ad5e9/src/gui/addnewtorrentdialog.cpp#L316-L319
- torrent downloading finished (actually HTML was downloaded), try to decode data https://github.com/c0re100/qBittorrent-Enhanced-Edition/blob/4ffc2ccce818b133e6355514234282e66c0ad5e9/src/gui/addnewtorrentdialog.cpp#L914
- error message about "bdecoded string" appears here https://github.com/c0re100/qBittorrent-Enhanced-Edition/blob/4ffc2ccce818b133e6355514234282e66c0ad5e9/src/base/bittorrent/torrentinfo.cpp#L95-L99
- error message is displayed, dot after URL you observed comes from here (it is after `%1`) https://github.com/c0re100/qBittorrent-Enhanced-Edition/blob/4ffc2ccce818b133e6355514234282e66c0ad5e9/src/gui/addnewtorrentdialog.cpp#L915-L920

so, there is **no issue with the torrent client**, the issue is only with the server supplying torrent files. please close the issue.

**Comment by Ding-Kyoma** [comment]
Thanks for your help!
